server:
  port: 10011
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10011/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false # 关闭自我保护模式，生成环境不配置
      #instance: #服务端
      #lease-expiration-duration-in-seconds: 10 # 10秒即过期，生成环境可默认(90)
      #lease-renewal-interval-in-seconds: 5 # 5秒一次心跳，生成环境可默认(30)
      #client: #消费端
    #registry-fetch-interval-seconds: 5
spring:
  application:
    name: demo-eureka